<?php
$data = array (
  0 => 
  array (
    'cat_id' => '53',
    'cat_name' => '全球购',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => '1',
  ),
  1 => 
  array (
    'cat_id' => '93',
    'cat_name' => '服装城',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '89',
    'cat_name' => '美妆馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => '1',
  ),
  3 => 
  array (
    'cat_id' => '45',
    'cat_name' => '零食馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => '1',
  ),
  4 => 
  array (
    'cat_id' => '82',
    'cat_name' => '数码馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => '6',
  ),
  5 => 
  array (
    'cat_id' => '84',
    'cat_name' => '百货馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => '3',
  ),
  6 => 
  array (
    'cat_id' => '81',
    'cat_name' => '玩具馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  7 => 
  array (
    'cat_id' => '1',
    'cat_name' => '蔬菜区',
    'commission' => '0.10',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '79',
    'cat_name' => '鲜果区',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => '12',
  ),
  9 => 
  array (
    'cat_id' => '48',
    'cat_name' => '水果区',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  10 => 
  array (
    'cat_id' => '122',
    'cat_name' => '休闲食品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '120',
    'cat_name' => '进口食品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '123',
    'cat_name' => '坚果蜜饯',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '86',
    'cat_name' => '全球特卖',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '8',
  ),
  14 => 
  array (
    'cat_id' => '100',
    'cat_name' => '母婴亲子',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '109',
    'cat_name' => '全球直采',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
  ),
  16 => 
  array (
    'cat_id' => '130',
    'cat_name' => '智能家居',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '125',
    'cat_name' => '平板电脑',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '128',
    'cat_name' => '网络产品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '126',
    'cat_name' => '摄影摄像',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '129',
    'cat_name' => '电子教育',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '127',
    'cat_name' => '摄影配件',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  22 => 
  array (
    'cat_id' => '121',
    'cat_name' => '地方特产',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '124',
    'cat_name' => '饮料冲调',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '134',
    'cat_name' => '韩国馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  25 => 
  array (
    'cat_id' => '143',
    'cat_name' => '美洲馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  26 => 
  array (
    'cat_id' => '132',
    'cat_name' => '日本馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  27 => 
  array (
    'cat_id' => '133',
    'cat_name' => '澳洲馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  28 => 
  array (
    'cat_id' => '142',
    'cat_name' => '欧洲馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  29 => 
  array (
    'cat_id' => '102',
    'cat_name' => '国际大牌',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  30 => 
  array (
    'cat_id' => '110',
    'cat_name' => '洗发护发',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '111',
    'cat_name' => '美体健齿',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '92',
    'cat_name' => '国际香水',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '98',
    'cat_name' => '大众经典',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '103',
    'cat_name' => '网红新贵',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '113',
    'cat_name' => '男装/内衣',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '116',
    'cat_name' => '精品户外',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '119',
    'cat_name' => '精品童装',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '114',
    'cat_name' => '精品鞋靴',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '117',
    'cat_name' => '精品箱包',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  40 => 
  array (
    'cat_id' => '112',
    'cat_name' => '女装/内衣',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '115',
    'cat_name' => '精品运动',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '118',
    'cat_name' => '珠宝/配饰',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '137',
    'cat_name' => '宝宝用品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  44 => 
  array (
    'cat_id' => '135',
    'cat_name' => '宝宝奶粉',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '138',
    'cat_name' => '宝宝洗护',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '136',
    'cat_name' => '宝宝食品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '139',
    'cat_name' => '宝宝营养',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '140',
    'cat_name' => '全球奶粉',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '141',
    'cat_name' => '全球纸尿裤',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>