<?php
$data = array (
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '全球购',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 0,
    'id' => '53',
    'name' => '全球购',
  ),
  86 => 
  array (
    'cat_id' => '86',
    'cat_name' => '全球特卖',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '8',
    'level' => 1,
    'id' => '86',
    'name' => '全球特卖',
  ),
  134 => 
  array (
    'cat_id' => '134',
    'cat_name' => '韩国馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '134',
    'name' => '韩国馆',
  ),
  143 => 
  array (
    'cat_id' => '143',
    'cat_name' => '美洲馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '143',
    'name' => '美洲馆',
  ),
  132 => 
  array (
    'cat_id' => '132',
    'cat_name' => '日本馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '132',
    'name' => '日本馆',
  ),
  133 => 
  array (
    'cat_id' => '133',
    'cat_name' => '澳洲馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '133',
    'name' => '澳洲馆',
  ),
  142 => 
  array (
    'cat_id' => '142',
    'cat_name' => '欧洲馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '86',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '142',
    'name' => '欧洲馆',
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '母婴亲子',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '100',
    'name' => '母婴亲子',
  ),
  137 => 
  array (
    'cat_id' => '137',
    'cat_name' => '宝宝用品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '137',
    'name' => '宝宝用品',
  ),
  135 => 
  array (
    'cat_id' => '135',
    'cat_name' => '宝宝奶粉',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '135',
    'name' => '宝宝奶粉',
  ),
  138 => 
  array (
    'cat_id' => '138',
    'cat_name' => '宝宝洗护',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '138',
    'name' => '宝宝洗护',
  ),
  136 => 
  array (
    'cat_id' => '136',
    'cat_name' => '宝宝食品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '136',
    'name' => '宝宝食品',
  ),
  139 => 
  array (
    'cat_id' => '139',
    'cat_name' => '宝宝营养',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '100',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '139',
    'name' => '宝宝营养',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '全球直采',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
    'level' => 1,
    'id' => '109',
    'name' => '全球直采',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => '全球奶粉',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '140',
    'name' => '全球奶粉',
  ),
  141 => 
  array (
    'cat_id' => '141',
    'cat_name' => '全球纸尿裤',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '109',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '141',
    'name' => '全球纸尿裤',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '服装城',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '93',
    'name' => '服装城',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '男装/内衣',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '113',
    'name' => '男装/内衣',
  ),
  116 => 
  array (
    'cat_id' => '116',
    'cat_name' => '精品户外',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '116',
    'name' => '精品户外',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '精品童装',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '119',
    'name' => '精品童装',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '精品鞋靴',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '114',
    'name' => '精品鞋靴',
  ),
  117 => 
  array (
    'cat_id' => '117',
    'cat_name' => '精品箱包',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '117',
    'name' => '精品箱包',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '女装/内衣',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '112',
    'name' => '女装/内衣',
  ),
  115 => 
  array (
    'cat_id' => '115',
    'cat_name' => '精品运动',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '115',
    'name' => '精品运动',
  ),
  118 => 
  array (
    'cat_id' => '118',
    'cat_name' => '珠宝/配饰',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '93',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '118',
    'name' => '珠宝/配饰',
  ),
  89 => 
  array (
    'cat_id' => '89',
    'cat_name' => '美妆馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => '1',
    'level' => 0,
    'id' => '89',
    'name' => '美妆馆',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '国际大牌',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '102',
    'name' => '国际大牌',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '洗发护发',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '110',
    'name' => '洗发护发',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '美体健齿',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '111',
    'name' => '美体健齿',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => '国际香水',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '92',
    'name' => '国际香水',
  ),
  98 => 
  array (
    'cat_id' => '98',
    'cat_name' => '大众经典',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '98',
    'name' => '大众经典',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '网红新贵',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '89',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '103',
    'name' => '网红新贵',
  ),
  45 => 
  array (
    'cat_id' => '45',
    'cat_name' => '零食馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '3',
    'goods_num' => '1',
    'level' => 0,
    'id' => '45',
    'name' => '零食馆',
  ),
  122 => 
  array (
    'cat_id' => '122',
    'cat_name' => '休闲食品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '122',
    'name' => '休闲食品',
  ),
  120 => 
  array (
    'cat_id' => '120',
    'cat_name' => '进口食品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '120',
    'name' => '进口食品',
  ),
  123 => 
  array (
    'cat_id' => '123',
    'cat_name' => '坚果蜜饯',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '123',
    'name' => '坚果蜜饯',
  ),
  82 => 
  array (
    'cat_id' => '82',
    'cat_name' => '数码馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => '6',
    'level' => 0,
    'id' => '82',
    'name' => '数码馆',
  ),
  130 => 
  array (
    'cat_id' => '130',
    'cat_name' => '智能家居',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '130',
    'name' => '智能家居',
  ),
  125 => 
  array (
    'cat_id' => '125',
    'cat_name' => '平板电脑',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '125',
    'name' => '平板电脑',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '网络产品',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '128',
    'name' => '网络产品',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '摄影摄像',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '126',
    'name' => '摄影摄像',
  ),
  129 => 
  array (
    'cat_id' => '129',
    'cat_name' => '电子教育',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '129',
    'name' => '电子教育',
  ),
  127 => 
  array (
    'cat_id' => '127',
    'cat_name' => '摄影配件',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '82',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '127',
    'name' => '摄影配件',
  ),
  84 => 
  array (
    'cat_id' => '84',
    'cat_name' => '百货馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => '3',
    'level' => 0,
    'id' => '84',
    'name' => '百货馆',
  ),
  121 => 
  array (
    'cat_id' => '121',
    'cat_name' => '地方特产',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '121',
    'name' => '地方特产',
  ),
  124 => 
  array (
    'cat_id' => '124',
    'cat_name' => '饮料冲调',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '84',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '124',
    'name' => '饮料冲调',
  ),
  81 => 
  array (
    'cat_id' => '81',
    'cat_name' => '玩具馆',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '81',
    'name' => '玩具馆',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '蔬菜区',
    'commission' => '0.10',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '蔬菜区',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '鲜果区',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 0,
    'id' => '79',
    'name' => '鲜果区',
  ),
  48 => 
  array (
    'cat_id' => '48',
    'cat_name' => '水果区',
    'commission' => '0.00',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 0,
    'id' => '48',
    'name' => '水果区',
  ),
);
?>